spring.config.import=optional:classpath:application-local.properties

# ===============================
# CONFIGURAÇÃO DO SERVIDOR
# ===============================
server.port=3000

# ===============================
# CONEXÃO COM O BANCO (NEON)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-wandering-king-anhyjf3a-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONFIGURAÇÕES DE SEGURANÇA
# ===============================
# CORREÇÃO: Adicionado valor default para evitar erro 500 se a variável JWT_SECRET_KEY estiver vazia
api.security.token.secret=${JWT_SECRET_KEY:3d990d2276917df5b044d28fca934e6a}


# REFATORADO: Adicionado suporte a múltiplas origens para o CORS.
api.security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}